### ISSUE TITLE
"No module named 'pmaw'" Error

### ISSUE THREAD

**Issue by Yuxcool** [De-y/reddit-karma-bot#1]
I get the error "Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/./src/init.py", line 6, in <module>
    import bot
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/src/bot.py", line 3, in <module>
    from bots.reddit import RedditBot
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/src/bots/reddit/__init__.py", line 3, in <module>
    from .bot import RedditBot
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/src/bots/reddit/bot.py", line 3, in <module>
    from apis import reddit_api
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/src/apis/__init__.py", line 5, in <module>
    from .pushshift import PS
  File "/Users/mac/PycharmProjects/reddit-karma-farming-bot-main/src/apis/pushshift.py", line 4, in <module>
    from pmaw import PushshiftAPI
ModuleNotFoundError: No module named 'pmaw'" when running the bot on macOS. 
![截屏 2](https://github.com/De-y/reddit-karma-farming-bot/assets/126325221/515e4e50-55eb-4022-b41e-b7e0154f5f34)

**Comment by lamettrist** [comment]
Hi there!

Have you tried installing from requirements.txt? If not, then you will need to run

``pip install psaw pmaw``

As these 2 libraries are in the requirements.txt

**Comment by lamettrist** [comment]
Closing issue as it has been a while.
